version: "2"

run:
  timeout: 5m

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - misspell
    - revive

  settings:
    revive:
      rules:
        - name: exported
          severity: warning
        - name: var-naming
          severity: warning

issues:
  max-same-issues: 0
  max-issues-per-linter: 0
